// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGUqCm7BSA7NBuOK5XSZwd1imvfqec5x4',
    appId: '1:425991075433:android:6948652c64c0c70460d4f8',
    messagingSenderId: '425991075433',
    projectId: 'starkey',
    databaseURL: 'https://starkey.firebaseio.com',
    storageBucket: 'starkey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm09RB7IqmHX2TplSqJtVebxZPv3oVAks',
    appId: '1:425991075433:ios:becc7edef6e15a9c60d4f8',
    messagingSenderId: '425991075433',
    projectId: 'starkey',
    databaseURL: 'https://starkey.firebaseio.com',
    storageBucket: 'starkey.firebasestorage.app',
    androidClientId:
        '425991075433-k2nngvktmvqcntrhspmt9cg5immvjrq0.apps.googleusercontent.com',
    iosClientId:
        '425991075433-96solm3887stnj7tpes3th0g0v6pu4sq.apps.googleusercontent.com',
    iosBundleId: 'com.starkey.manager.customerManagerNative',
  );
}
